### PR TITLE
Add support for Palm, Claude-2, Llama2, CodeLlama (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM allows you to use any LLM as a drop in replacement for `gpt-3.5-turbo` 

In addition LiteLLM client allows you to:
* A/B test LLMs in production 
* Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)
* Logging to view input/outputs for each LLM

Here's a link to a live demo of litellm client: https://admin.litellm.ai/ 

liteLLM-Ab-testing

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@oliverfeng @uni-zhuan  can I get a review on this PR ? 

Happy to add docs/tests if this initial commit looks good😊

**Comment by crazycth** [comment]
@ishaan-jaff  Hello😺

litellm looks really coooool~~

Could you please add dependencies after you import litellm

do this like `poetry add litellm`

**Comment by ishaan-jaff** [comment]
@crazycth updated ! any other suggested changes ?

**Comment by crazycth** [comment]
@ishaan-jaff we have use litellm in our latest pr : https://github.com/YiVal/YiVal/pull/81

and also support model comparison

I'll close this pr and thanks for litellm!!!

**Pull request closed without merging**
